spring.application.name=StudyAI
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/studyai}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
study-ai.storage.upload-dir=uploads
# Configure a separate Ollama embedding model, for example: nomic-embed-text.
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5-coder:3b
